### ISSUE TITLE
Test with Python 3

### ISSUE THREAD

**Issue by jenshnielsen** [DCPROGS/HJCFIT#71]
We should test the code on at least one platform using python3

**Comment by jenshnielsen** [comment]
Currently it errors with something like:
```
Feature: QMatrix bindings
  The following tests the c++ to python bindings of QMatrix. Most of the tests are about making
  sure that c++ objects are translated correctly, or signal somehow that translation could not
  happen. Sometimes the bindings are shallow wrappers around c++ objects. Othertimes they may copies
  of c++ objects. In any case, values modified in python should be reflected in C and vice-versa.
  Below, a "numpy array" is a python object which represents a matrix.
  Scenario: Initialize empty matrix
    Given QMatrix is accessible
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "../../../../../../likelihood/python/features/steps/qmatrix.py", line 24, in step
          from dcprogs.likelihood import QMatrix
        File "/Users/jhn/ucl/dcprogs/HJCFIT/build/test-results/install/lib/python3.5/site-packages/dcprogs/__init__.py", line 22, in <module>
          from . import likelihood
        File "/Users/jhn/ucl/dcprogs/HJCFIT/build/test-results/install/lib/python3.5/site-packages/dcprogs/likelihood/__init__.py", line 19, in <module>
          from .likelihood import *
        File "/Users/jhn/ucl/dcprogs/HJCFIT/build/test-results/install/lib/python3.5/site-packages/dcprogs/likelihood/likelihood.py", line 94
          def _dcprogs_dtype() -> "PyObject *":
                               ^
      SyntaxError: invalid syntax
```

**Comment by jenshnielsen** [comment]
This seems to be due to swig using python 3 function annotations. These changed in python 3.5 so the swig syntax is no longer valid. See https://www.python.org/dev/peps/pep-3107/#rationale and https://docs.python.org/3/whatsnew/3.5.html  removing the python 3 option in `likelihood/python/CMakeLists.txt` (according to the swig docs this is optional and swig should work for python3 even without this flag) seems to make it go a bit further and failing with a different error

```
Feature: QMatrix bindings
  The following tests the c++ to python bindings of QMatrix. Most of the tests are about making
  sure that c++ objects are translated correctly, or signal somehow that translation could not
  happen. Sometimes the bindings are shallow wrappers around c++ objects. Othertimes they may copies
  of c++ objects. In any case, values modified in python should be reflected in C and vice-versa.
  Below, a "numpy array" is a python object which represents a matrix.
  Scenario: Initialize empty matrix
    Given QMatrix is accessible
      Traceback (most recent call last):
        File "/usr/local/lib/python2.7/site-packages/behave/model.py", line 1456, in run
          match.run(runner.context)
        File "/usr/local/lib/python2.7/site-packages/behave/model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "../../../../../../likelihood/python/features/steps/qmatrix.py", line 24, in step
          from dcprogs.likelihood import QMatrix
        File "/Users/jhn/ucl/dcprogs/HJCFIT/build/test-results/install/lib/python3.5/site-packages/dcprogs/__init__.py", line 22, in <module>
          from . import likelihood
        File "/Users/jhn/ucl/dcprogs/HJCFIT/build/test-results/install/lib/python3.5/site-packages/dcprogs/likelihood/__init__.py", line 19, in <module>
          from .likelihood import *
        File "/Users/jhn/ucl/dcprogs/HJCFIT/build/test-results/install/lib/python3.5/site-packages/dcprogs/likelihood/likelihood.py", line 28, in <module>
          _likelihood = swig_import_helper()
        File "/Users/jhn/ucl/dcprogs/HJCFIT/build/test-results/install/lib/python3.5/site-packages/dcprogs/likelihood/likelihood.py", line 24, in swig_import_helper
          _mod = imp.load_module('_likelihood', fp, pathname, description)
      ImportError: dynamic module does not define init function (init_likelihood)
```

**Comment by jenshnielsen** [comment]
It seems to be working now that we have switched to cookoff. Probably the above errors were caused by mixed headers and libraries or some such thing.

**Comment by raquel-ucl** [comment]
Should this be a separate job or a modification in the current ones?

**Comment by jenshnielsen** [comment]
IMHO We should add another axis to the job and run with python 3 on legion

**Comment by raquel-ucl** [comment]
OK, I'll do when I finish this other stuff.

**Comment by jenshnielsen** [comment]
Hopefully it is simple :wink:

**Comment by raquel-ucl** [comment]
Seems like it works in staging RHEL after changing the `testingBundles` for DCPROGS in Legion to remove the `module load` sentence for python. It still needs to be merged to master. I'll make a pull request in the Jenkins repo with the latests changes.

**Comment by jenshnielsen** [comment]
Works on legion with python3.4 would be nice to have python3.5 on OSX or windows too
